name: Package Windows Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Package
      run: pip install .

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package Application
      run: pyinstaller --clean -y --dist ./dist/windows --workpath /tmp sjtu-schedule-exporter-cli.spec

    - uses: actions/upload-artifact@v2
      with:
        name: sjtu-schedule-exporter-cli.exe
        path: dist/windows